facility: sandbox
log_level: debug
endpoints:
  fleetdb:
    authenticate: false
    oidc_audience_url:
    oidc_client_id:
    oidc_issuer_url:
    oidc_client_scopes:
    url: http://fleetdb:8000
  conditionorc:
    authenticate: false
    oidc_audience_url:
    oidc_client_id:
    oidc_issuer_url:
    oidc_client_scopes:
    url: http://conditionorc:9001
  otel:
    authenticate: false
    url: jaeger:4317