log_level: debug
store_kind: fleetscheduler
facility_code: sandbox
fleetdb_api:
  endpoint: http://localhost:8000
  disable_oauth: false
conditionorc_api:
  endpoint: http://localhost:9001
  disable_oauth: false