log_level: debug
facility_code: sandbox
concurrency: 4 # max thread count allowed for communicating with other resources
fleetdb_api:
  endpoint: http://localhost:8000
  disable_oauth: true
conditionorc_api:
  endpoint: http://localhost:9001
  disable_oauth: true