log_level: debug
store_kind: fleetscheduler
facility_code: fr9
fleetdb_api:
  endpoint: http://192.168.1.191:8000
  disable_oauth: true
conditionorc_api:
  endpoint: http://192.168.1.191:9001
  disable_oauth: true