name: lint, test and build image
on: [pull_request, push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        skip-cache: true
        args: --config .golangci.yaml --timeout 2m
        version: v1.61.0
    - name: Test
      run: go test ./...
  build:
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: build binary
        run: make build-linux

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Fleet Scheduler Docker image - no push
        id: dockerbuild-fleet-scheduler
        uses: docker/build-push-action@v6
        with:
           context: .
           push: false
           tags: ghcr.io/metal-toolbox/fleet-scheduler:latest
           file: Dockerfile

      - name: Scan image - Fleet Scheduler
        id: scan-fleet-scheduler-image
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/metal-toolbox/fleet-scheduler:latest
          acs-report-enable: true
          fail-build: false

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
        # This should run even if we fail the container scan
        if: always()
